### ISSUE TITLE
User Mananagement Load er ekstrem langsom.

### ISSUE THREAD

**Issue by itsdanieldk** [trolund/11_CDIO_FINAL#19]
Når man går ind på web interfacet og trykker på User Management, så går det 3-5 sekunder gør at brugerne bliver vist. Det har ikke været så langsomt som det er nu, og det ville være fedt hvis vi kunne få det til at gøres hurtigere.

Til dette skal der nok involveres noget performance debugging.

**Comment by trolund** [comment]
loading af kode er blivet flyttet ud så det kun sker en gang. ser ud til at det er noget hurtigere nu.
